-- MySQL Script generated by MySQL Workbench
-- 08/02/15 08:00:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema trust
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trust
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trust` DEFAULT CHARACTER SET utf8 ;
USE `trust` ;

-- -----------------------------------------------------
-- Table `trust`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trust`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(8) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `dataRecebimento` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `endTrabalho` VARCHAR(255) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `referencia` VARCHAR(255) NULL DEFAULT NULL,
  `SITUACAO` VARCHAR(255) NULL DEFAULT NULL,
  `telCelular` VARCHAR(45) NULL DEFAULT NULL,
  `telContato` VARCHAR(45) NULL DEFAULT NULL,
  `telFixo` VARCHAR(45) NULL DEFAULT NULL,
  `UF` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trust`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trust`.`venda` (
  `idVenda` INT(11) NOT NULL AUTO_INCREMENT,
  `dataVenda` DATE NOT NULL,
  `entrada` DECIMAL(9,2) NOT NULL,
  `parcelas` INT(11) NOT NULL,
  `quitada` TINYINT(1) NOT NULL DEFAULT '0',
  `qutPecas` INT(11) NULL DEFAULT NULL,
  `recebido` DECIMAL(9,2) NOT NULL,
  `total` DECIMAL(9,2) NOT NULL,
  `idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `FK_venda_idCliente` (`idCliente` ASC),
  CONSTRAINT `FK_venda_idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `trust`.`cliente` (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trust`.`parcela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trust`.`parcela` (
  `idParcela` INT(11) NOT NULL AUTO_INCREMENT,
  `numeroDaParcela` INT(11) NOT NULL,
  `pago` TINYINT(1) NOT NULL DEFAULT '0',
  `recebido` DECIMAL(9,2) NOT NULL,
  `valor` DECIMAL(9,2) NOT NULL,
  `vencimento` DATE NOT NULL,
  `idVenda` INT(11) NOT NULL,
  PRIMARY KEY (`idParcela`),
  INDEX `FK_parcela_idVenda` (`idVenda` ASC),
  CONSTRAINT `FK_parcela_idVenda`
    FOREIGN KEY (`idVenda`)
    REFERENCES `trust`.`venda` (`idVenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
